version: "3.7"

# environment
x-volumes: &env-volume
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "uwqr82asfg298ruwh1234uchrbgyu2oriqwnetge5rteriyu2354f3erfewc"

  MONGO_URL: "mongodb://root:password@db:27017/blog_db_new?authSource=admin"
  DEBUG: "True"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayan32biswas/fastapi_blog:latest
    container_name: fastapi_blog_server
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    environment:
      <<: *env-volume
    # env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - blog-backend-tier

  db:
    image: mongo
    # restart: always
    container_name: fastapi_blog_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - blog-db:/data/db
    networks:
      - blog-backend-tier

volumes:
  blog-db:
    driver: local

networks:
  blog-backend-tier:
    driver: bridge
